### ISSUE TITLE
官网首页展示问题

### ISSUE THREAD

**Issue by hisaspirations** [CHCP/toolmaker#2]
![image](https://user-images.githubusercontent.com/5309179/60695104-24140e80-9f13-11e9-857d-e8a697de64df.png)

**Comment by rts-gordon** [comment]
Hi @CrouchingTigerM ,
   前端使用的部分图标存放在googleapi.com网站上，刷新下就可以。如果还不可以的话，只能翻墙了。后期我们优化下。

谢谢使用。

**Comment by rts-gordon** [comment]
我们重新发布了前端程序，把这些icons都打包发布，现在无论是否翻墙都可以访问了。请使用。
